# This is the final, correct, and definitive docker-compose.yml for a DEVELOPMENT environment.

services:
  app:
    # Build the image using our new development Dockerfile
    build: .
    container_name: x_models_app
    ports:
      - "3000:3000"

    # This correctly mounts our local code for live-reloading
    # and creates a separate volume for node_modules to prevent conflicts.
    volumes:
      - .:/app
      - node_modules_volume:/app/node_modules

    depends_on:
      db:
        condition: service_healthy

    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

  db:
    image: postgres:16-alpine
    container_name: x_models_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  node_modules_volume: {}
